In [3]:
import numpy as np

In [14]:
x = [[1,2],[3,4]]
total = 0
for i in x:
   total = total +sum(i)
print(total)

10


In [20]:
x = [[1,2],[3,4]]
nx = np.array(x)
print(nx)
print(nx.sum())
print(nx.min())
print(nx.max())
print(nx.mean())
print(nx.std())
print(nx.var())
type(nx)
print(nx.shape)  # shape of matrix
print(nx.size)   # total elements
print(nx.dtype)  # type of elements


[[1 2]
 [3 4]]
10
1
4
2.5
1.118033988749895
1.25
(2, 2)
4
int64


In [25]:
x = [[1,2,3],[3,4,3],[1,2,3]]
nx = np.array(x)
print(nx)

[[1 2 3]
 [3 4 3]
 [1 2 3]]


# Funtions to create matrix
- arange- create a range of numbers 
- linspace- create a matrox of specified numbers of elements
- ones- cteate a matrix of ones
- zeors- create a matrix of zeros
- random.rand- create a matrix of random floats
- diag- create a matrix with diagonal elements 

In [31]:
a = np.arange(1, 51)
print(a)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
[1.    1.002 1.004 ... 4.994 4.996 4.998]


In [35]:
print(np.arange(1, 5, .02))

[1.   1.02 1.04 1.06 1.08 1.1  1.12 1.14 1.16 1.18 1.2  1.22 1.24 1.26
 1.28 1.3  1.32 1.34 1.36 1.38 1.4  1.42 1.44 1.46 1.48 1.5  1.52 1.54
 1.56 1.58 1.6  1.62 1.64 1.66 1.68 1.7  1.72 1.74 1.76 1.78 1.8  1.82
 1.84 1.86 1.88 1.9  1.92 1.94 1.96 1.98 2.   2.02 2.04 2.06 2.08 2.1
 2.12 2.14 2.16 2.18 2.2  2.22 2.24 2.26 2.28 2.3  2.32 2.34 2.36 2.38
 2.4  2.42 2.44 2.46 2.48 2.5  2.52 2.54 2.56 2.58 2.6  2.62 2.64 2.66
 2.68 2.7  2.72 2.74 2.76 2.78 2.8  2.82 2.84 2.86 2.88 2.9  2.92 2.94
 2.96 2.98 3.   3.02 3.04 3.06 3.08 3.1  3.12 3.14 3.16 3.18 3.2  3.22
 3.24 3.26 3.28 3.3  3.32 3.34 3.36 3.38 3.4  3.42 3.44 3.46 3.48 3.5
 3.52 3.54 3.56 3.58 3.6  3.62 3.64 3.66 3.68 3.7  3.72 3.74 3.76 3.78
 3.8  3.82 3.84 3.86 3.88 3.9  3.92 3.94 3.96 3.98 4.   4.02 4.04 4.06
 4.08 4.1  4.12 4.14 4.16 4.18 4.2  4.22 4.24 4.26 4.28 4.3  4.32 4.34
 4.36 4.38 4.4  4.42 4.44 4.46 4.48 4.5  4.52 4.54 4.56 4.58 4.6  4.62
 4.64 4.66 4.68 4.7  4.72 4.74 4.76 4.78 4.8  4.82 4.84 4.86 4.88 4.9
 4.92 4.9

In [40]:
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [52]:
print(np.ones(10))
print("\n")
print(np.ones((3,3)))
print("\n")
np.ones((4,4), dtype=int)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]




array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [55]:
print(np.zeros(4))

[0. 0. 0. 0.]


In [57]:
np.random.randint(1, 100, 10)

array([28, 15, 31, 85, 86,  5, 73, 57, 89, 55])

In [58]:
np.random.randint(-5, 6, (5,5))

array([[ 5,  0, -3,  3, -2],
       [-3,  4,  4,  0,  5],
       [ 4,  5, -5,  2,  5],
       [ 4,  3,  2,  2, -1],
       [ 4,  2,  5,  0, -5]])

In [60]:
np.random.rand(5)  # num of elements 

array([0.9293356 , 0.33274404, 0.56883273, 0.31277856, 0.28689472])

In [61]:
np.random.rand(10,5)   # 10 *10 matrix 

array([[0.14605583, 0.97315173, 0.46803008, 0.73721686, 0.73665926],
       [0.49322737, 0.63165354, 0.7495048 , 0.71836558, 0.5450252 ],
       [0.35751497, 0.45949019, 0.29689341, 0.65924838, 0.99481811],
       [0.35551378, 0.31079961, 0.19852612, 0.95946726, 0.75482878],
       [0.20531854, 0.62269121, 0.93608384, 0.31093572, 0.21332349],
       [0.74525708, 0.43533306, 0.74005903, 0.81677992, 0.31127817],
       [0.47484538, 0.38646883, 0.86489511, 0.84491464, 0.37906836],
       [0.33882342, 0.07970431, 0.65862107, 0.30330558, 0.31706131],
       [0.47232441, 0.13642309, 0.28593086, 0.88985618, 0.73174856],
       [0.06990507, 0.09347034, 0.90850583, 0.64881124, 0.3925553 ]])

In [62]:
np.set_printoptions(precision=3)    # set precision to 3
np.random.rand(10,5)

array([[0.696, 0.059, 0.299, 0.368, 0.987],
       [0.064, 0.891, 0.08 , 0.34 , 0.093],
       [0.612, 0.177, 0.092, 0.077, 0.816],
       [0.967, 0.382, 0.121, 0.215, 0.393],
       [0.966, 0.944, 0.593, 0.455, 0.887],
       [0.176, 0.563, 0.919, 0.891, 0.874],
       [0.632, 0.855, 0.488, 0.148, 0.705],
       [0.566, 0.189, 0.161, 0.493, 0.243],
       [0.203, 0.063, 0.096, 0.456, 0.892],
       [0.797, 0.993, 0.332, 0.997, 0.667]])

In [64]:
a = [1,2,3,4,5,6,7,8,9]
np.diag(a)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [70]:
# reshape 
print(np.arange(10).reshape(2,5))
print(np.arange(10).reshape(5,2))
print(np.arange(10).reshape(1,10))
print(np.arange(10).reshape(10,1))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1 2 3 4 5 6 7 8 9]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [79]:
b = np.linspace(1, 5, 25).reshape(5,5)
print(b)

[[1.    1.167 1.333 1.5   1.667]
 [1.833 2.    2.167 2.333 2.5  ]
 [2.667 2.833 3.    3.167 3.333]
 [3.5   3.667 3.833 4.    4.167]
 [4.333 4.5   4.667 4.833 5.   ]]


In [80]:
b.flatten()

array([1.   , 1.167, 1.333, 1.5  , 1.667, 1.833, 2.   , 2.167, 2.333,
       2.5  , 2.667, 2.833, 3.   , 3.167, 3.333, 3.5  , 3.667, 3.833,
       4.   , 4.167, 4.333, 4.5  , 4.667, 4.833, 5.   ])

In [81]:
y = np.arange(1, 26).reshape(5,5)
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [82]:
y.transpose()

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

In [87]:
# Maths 

a = np.random.randint(1,10,(3,3))
b = np.random.randint(1,10,(3,3))
print(a)
print("\n")
print(b)
print("\n")
print(a+b)
print("\n")
print(a-b)
print("\n")
print(a*b)
print("\n")
print(a/b)

[[9 1 1]
 [6 6 6]
 [8 8 8]]


[[2 5 1]
 [8 5 2]
 [6 4 7]]


[[11  6  2]
 [14 11  8]
 [14 12 15]]


[[ 7 -4  0]
 [-2  1  4]
 [ 2  4  1]]


[[18  5  1]
 [48 30 12]
 [48 32 56]]


[[4.5   0.2   1.   ]
 [0.75  1.2   3.   ]
 [1.333 2.    1.143]]


In [88]:
a.dot(b)  # dot product (matrix multiplication)

array([[ 32,  54,  18],
       [ 96,  84,  60],
       [128, 112,  80]])

In [90]:
a + 10

array([[19, 11, 11],
       [16, 16, 16],
       [18, 18, 18]])

In [96]:
# Stats 

print(a.mean())
print(a.mean(axis=0))  # column wise mean
print(a.mean(axis=1))  # row wise mean 
print(a.sum(axis=0))   # column wise sum
print(a.sum(axis=1))   # row wise sum 

5.888888888888889
[7.667 5.    5.   ]
[3.667 6.    8.   ]
[23 15 15]
[11 18 24]


In [103]:
print(np.sin(a))


print(np.cos(a))


print(np.tan(a))

[[ 0.412  0.841  0.841]
 [-0.279 -0.279 -0.279]
 [ 0.989  0.989  0.989]]
[[-0.911  0.54   0.54 ]
 [ 0.96   0.96   0.96 ]
 [-0.146 -0.146 -0.146]]
[[-0.452  1.557  1.557]
 [-0.291 -0.291 -0.291]
 [-6.8   -6.8   -6.8  ]]


In [104]:
print(np.exp(a))
print(np.max(a))
print(np.min(a))
print(np.exp(a))
print(np.exp(a))

[[8.103e+03 2.718e+00 2.718e+00]
 [4.034e+02 4.034e+02 4.034e+02]
 [2.981e+03 2.981e+03 2.981e+03]]


In [5]:
x = np.random.randint(1, 100, (2,5))
print(x)

[[61 98 89 37 24]
 [18 84 56 59 44]]


In [6]:
print(x.max())     # max element
print(x.argmax())  # index of max element 
print(x.min())     # min element 
print(x.argmin())  # index of min element

98
1
18
5
